version: "3.5"

networks: 
  net-project:
    name: net-project
    driver: bridge
    ipam: 
      driver: default
      config:
        - subnet: 10.1.0.0/24

services:
  auth:
    hostname: auth
    build: 
      context: .docker/python
      dockerfile: Dockerfile
    labels:
      com.dev.linux.author: "Andre L S Ferreira"
      com.dev.linux.description: "Learning about structure JWT server in Python"
      com.dev.linux.license: "MIT"
    env_file:
      - ./.docker/python/.env
    volumes:
      - ./auth:/usr/src/app
    expose:
      - 5000
    restart: 
      on-failure
    links: 
      - postgres-server
    extra_hosts: 
      - "postgres-server:10.1.0.3"
      - "backend-server:10.1.0.4"
    depends_on: 
      - postgres-server
    networks: 
      net-project:
        ipv4_address: "10.1.0.2"
  
  postgres-server:
    hostname: postgres-server
    build:
      context: ./.docker/postgres/docker
      dockerfile: Dockerfile
    env_file: 
      - ./.docker/postgres/docker/.env
    volumes: 
      - ./.docker/postgres/data:/var/lib/postgresql/data/
    expose: 
      - 5432
    networks: 
      net-project:
        ipv4_address: "10.1.0.3"

  backend:
    hostname: backend-server
    build: ./.docker/apache
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "80:80"
    links:
      - mysql-server
      - auth
    depends_on: 
      - mysql-server
    restart:
      on-failure
    extra_hosts:
      - "mysql-server:10.1.0.5"
      - "auth:10.1.0.2"
    networks:
      net-project:
        ipv4_address: "10.1.0.4"

  mysql-server:
    hostname: mysql-server
    image: mysql:5.7
    env_file:
      - ./.docker/mysql/.env
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    expose:
      - 3306
    restart:
      on-failure
    networks:
      net-project:
        ipv4_address: "10.1.0.5"