version: "3.5"

networks: 
  net-project:
    name: net-project
    driver: bridge
    ipam: 
      driver: default
      config:
        - subnet: 10.1.0.0/24

services:
  auth:
    hostname: auth
    build: 
      context: .docker/python
      dockerfile: Dockerfile
    labels:
      com.dev.linux.author: "Andre Ferreira"
      com.dev.linux.description: "Auth JWT server in Python"
      com.dev.linux.license: "MIT"
    env_file:
      - ./.docker/python/.env
    volumes:
      - ./auth:/usr/src/app
    expose:
      - 5000
    restart: 
      on-failure
    links: 
      - auth-db
    extra_hosts: 
      - "auth-db:10.1.0.3"
      - "backend-server:10.1.0.4"
    depends_on: 
      - auth-db
    networks: 
      net-project:
        ipv4_address: "10.1.0.2"
  
  auth-db:
    hostname: auth-db
    build:
      context: ./.docker/auth-db
      dockerfile: Dockerfile
    labels:
      com.dev.linux.author: "Andre Ferreira"
      com.dev.linux.description: "Database PostgreSQL Auth"
      com.dev.linux.license: "MIT"
    env_file: 
      - ./.docker/auth-db/.env
    volumes: 
      - ./.docker/auth-db/data:/var/lib/postgresql/data/
    expose: 
      - 5432
    networks: 
      net-project:
        ipv4_address: "10.1.0.3"

  backend:
    hostname: backend-server
    build: 
      context: ./.docker/apache
      dockerfile: Dockerfile
    labels:
      com.dev.linux.author: "Andre Ferreira"
      com.dev.linux.description: "Apache Server and PHP Slim"
      com.dev.linux.license: "MIT"
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "80:80"
    links:
      - backend-db
      - auth
    depends_on: 
      - backend-db
    restart:
      on-failure
    extra_hosts:
      - "backend-db:10.1.0.5"
      - "auth:10.1.0.2"
    networks:
      net-project:
        ipv4_address: "10.1.0.4"

  backend-db:
    hostname: backend-db
    build:
      context: ./.docker/backend-db
      dockerfile: Dockerfile
    labels:
      com.dev.linux.author: "Andre Ferreira"
      com.dev.linux.description: "Database PostgreSQL Backend"
      com.dev.linux.license: "MIT"
    env_file:
      - ./.docker/backend-db/.env
    volumes:
      - ./.docker/backend-db/data:/var/lib/postgresql/data/
    expose:
      - 5432
    restart:
      on-failure
    networks:
      net-project:
        ipv4_address: "10.1.0.5"