version: "3.5"

networks: 
  net-flask-jwt:
    name: net-flask-jwt
    driver: bridge
    ipam: 
      driver: default
      config:
        - subnet: 10.62.0.0/24

services:
  flask-jwt:
    hostname: flask-jwt
    build: 
      context: .docker/python
      dockerfile: Dockerfile
    labels:
      com.dev.linux.author: "Andre L S Ferreira"
      com.dev.linux.description: "Learning about structure JWT server in Python"
      com.dev.linux.license: "MIT"
    env_file:
      - ./.docker/python/.env
    volumes:
      - ./flask-jwt:/usr/src/app
    ports:
      - "80:5000"
    restart: 
      on-failure
    links: 
      - postgres-server
    extra_hosts: 
      - "postgres-server:10.62.0.3"
    depends_on: 
      - postgres-server
    networks: 
      net-flask-jwt:
        ipv4_address: "10.62.0.2"
  
  postgres-server:
    hostname: postgres-server
    build:
      context: ./.docker/postgres/docker
      dockerfile: Dockerfile
    env_file: 
      - ./.docker/postgres/docker/.env
    volumes: 
      - ./.docker/postgres/data:/var/lib/postgresql/data/
    expose: 
      - 5432
    networks: 
      net-flask-jwt:
        ipv4_address: "10.62.0.3"